---
title: "ggsmock2_final.rmd"
author: "ian johnson"
date: "March 7, 2016"
output: html_document
---

```{r setup, include=FALSE}
# Put your libs here:
library(ncdf4)
library(ggplot2)
library(devtools)
library(ggbiplot)
library(lattice)

setwd('~/Desktop/Columbia/EDAV/Project2')

# Import the two datasets
ncin <- nc_open("NOAA_Daily_phi_500mb.nc")
flood_df = read.csv('GlobalFloodsRecord.csv', fileEncoding="macroman", stringsAsFactors = FALSE)
```





## Basic flood data
Here we show basic flooding statistics. The following graphs represent the number of flooding events per month for each year, and we can see that some years exhibit increased flooding in the late summer months. 

```{r scatterplot, fig.width=14, fig.height=14, echo=FALSE, results="hide"}
# Format dates for parsing
df_ian = data.frame(as.Date(flood_df$Began, "%e-%b-%y"))
names(df_ian) = c("newDate")
df_ian2 = subset(df_ian, newDate >= "1985-01-01" & newDate <= "2008-01-01")

##### Trellis plot for flood counts per year
histogram(
  ~factor(
    format(df_ian2$newDate,"%b"),
    levels = c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")
  ) | factor(
    format(df_ian2$newDate,"%y"),
    level = c("85", "86", "87", "88", "89", "90", "91", "92", "3", "94", "99", "00", "01", "02", "03", "04", "05", "06", "07", "08")
  ),
  data=df_ian2, layout=(c(3,6)),
  main="Flood Counts by year and month",
  ylab="Flood Count",
  xlab="Year"
)
```